### ISSUE TITLE
Upgrade Eloquent ServiceProvider to Silex 2.0

### ISSUE THREAD

**Issue by davincho** [BitolaCo/silex-eloquent#1]
Are you planning to make the Eloquent ServiceProvider available for Silex version 2.0 as well?

**Comment by ChunkRadius** [comment]
Good question. Honestly I haven't seen anything about Silex 2.0, but definitely, that would make sense. We use Silex a lot here at work, and no doubt will want to keep up with the latest version. You wouldn't happen to know off hand where docs can be located for upgrading providers? I've searched around just a little bit, but not found anything yet.

**Comment by ChunkRadius** [comment]
Hey @davincho I hacked something together today that is at least basically working for Eloquent 5.x and Silex 2.x, but it still needs a lot of testing. It's at least working on basic queries, but I'm not entirely how Eloquent has changed, and whether all of the config options are working.

If you have a few spare minutes, feel free to help out with testing. It's in the [silex-v2 branch](https://github.com/BitolaCo/silex-eloquent/tree/silex-v2).

I want to add unit tests so manually testing won't be necessary, but haven't gotten around to it, so if you're free to help out that would be much appreciated! :smile:

**Comment by davincho** [comment]
Hey @bradberger, sorry for my late reply. In the meanwhile we changed from Silex to Lumen (which supports Eloquent out of the box as Lumen is based on Laraval). Anyways, I am glad to help with some testing. Do you have anything special in mind? Test structure?

**Comment by ChunkRadius** [comment]
Actually I've done the same thing with Lumen, and so far so good. Now that Lumen is around, I'm note even sure there's advantage to maintaining this going forward. Any thoughts?

**Comment by davincho** [comment]
Well, in my opinion Silex slowly gets old-fashioned. I really like the way how Lumen does validation and encapsulation of database access. As Silex and Lumen are based on Symfony components, people who want to use Eloquent would probably switch to Lumen instead of using an EloquentServiceProvider. So my recommendation is to use your spare time for other projects ;)

**Comment by ChunkRadius** [comment]
Cool, thanks for your thoughts, I agree. Appreciate your taking the time to respond. Going to mark this as closed, in that case. Thanks!
